name: Code format
on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format -- --check
